In [1]:
import numpy as np

### Covariance matrix

In [3]:
# vector correlation

# define first vector
x = np.array([1,2,3,4,5,6,7,8,9])
print(x)
# define second vector
y = np.array([9,8,7,6,5,4,3,2,1])
print(y)
# calculate correlation
corr = np.corrcoef(x,y)[0,1]
print(corr)

[1 2 3 4 5 6 7 8 9]
[9 8 7 6 5 4 3 2 1]
-1.0


In [4]:
# covariance matrix

# define matrix of observations
X = np.array([
  [1, 5, 8],
  [3, 5, 11],
  [2, 4, 9],
  [3, 6, 10],
  [1, 5, 10]])
print(X)
# calculate covariance matrix
Sigma = np.cov(X.T)
print(Sigma)

[[ 1  5  8]
 [ 3  5 11]
 [ 2  4  9]
 [ 3  6 10]
 [ 1  5 10]]
[[1.   0.25 0.75]
 [0.25 0.5  0.25]
 [0.75 0.25 1.3 ]]
